"""export_model.py — write gen/model_params.h for the C build.

This generated header is the ONLY channel between training and flight. Bin
edges and weights travel together in one file, stamped with the constants they
were built for, so it is impossible to fly weights trained with a different
bin count or star cap without the C compiler noticing.

Run after train.py:
  python3 export_model.py
"""

import os
import json
from st_experiment import load_model
import numpy as np

GEN = os.environ.get("ST_GEN_DIR", os.path.join(os.path.dirname(__file__), "..", "gen"))
# Read back from the artifacts that training actually produced, so this file
# cannot describe a model different from the one in gen/. ST_NUM_CELLS lets the
# partition size be swept without editing code.
NUM_CELLS = int(os.environ.get("ST_NUM_CELLS", "529"))
from st_features import NUM_BINS, MAX_STARS
H1, H2 = 96, 96


def emit_array(f, name, arr):
    """Write a float array as a C initializer, 8 values per line.

    %.9g is the shortest decimal form that round-trips a 32-bit float exactly,
    so the compiled constants are bit-identical to what NumPy trained.
    """
    a = np.asarray(arr, dtype=np.float32).ravel()
    f.write(f"static const float {name}[{a.size}] = {{\n")
    for i in range(0, a.size, 8):
        chunk = ", ".join((lambda s: s if ("." in s or "e" in s) else s + ".0")(f"{v:.9g}") + "f" for v in a[i:i + 8])
        f.write(f"    {chunk},\n")
    f.write("};\n\n")


def main():
    m, metadata = load_model(GEN)
    cos_edges = np.load(os.path.join(GEN, "bins.npy")).astype(np.float32)

    assert cos_edges.size == NUM_BINS + 1, "bin edge count mismatch"
    assert np.all(np.diff(cos_edges) < 0), "cosine edges must be descending"
    assert m["W1"].shape == (H1, NUM_BINS), f"W1 is {m['W1'].shape}"
    assert m["W2"].shape == (H2, H1)
    assert m["W3"].shape == (NUM_CELLS, H2)

    path = os.path.join(GEN, "model_params.h")
    with open(path, "w") as f:
        f.write(f"""/* model_params.h — GENERATED by python/export_model.py. Do not edit.
 *
 * Trained model and histogram bin edges for the star tracker cell classifier.
 * Regenerate with:  python3 train.py && python3 export_model.py
 */
#ifndef ST_MODEL_PARAMS_H
#define ST_MODEL_PARAMS_H

#include "st_mlp.h"
#include "st_feature.h"

/* Compile-time guards: if the flight configuration and the trained model ever
 * disagree, the build fails here instead of the spacecraft failing in orbit. */
#if (ST_NUM_BINS != {NUM_BINS})
#error "ST_NUM_BINS does not match the trained model; retrain or fix st_config.h"
#endif
#if (ST_NUM_CELLS != {NUM_CELLS})
#error "ST_NUM_CELLS does not match the trained model"
#endif
#if (ST_H1 != {H1}) || (ST_H2 != {H2})
#error "hidden layer sizes do not match the trained model"
#endif
#if (ST_MAX_STARS != {MAX_STARS})
#error "ST_MAX_STARS differs from the value the model was trained with"
#endif

""")
        for key,value in metadata["camera"].items():
            f.write(f"#define ST_TRAIN_{key.upper()} {float(value):.9e}f\n")
        f.write("/* Experiment identity: " + metadata["bins_sha256"] + " */\n")
        emit_array(f, "ST_COS_EDGES", cos_edges)
        emit_array(f, "ST_IN_MEAN", m["in_mean"])
        emit_array(f, "ST_IN_SCALE", m["in_scale"])
        emit_array(f, "ST_W1", m["W1"])
        emit_array(f, "ST_B1", m["b1"])
        emit_array(f, "ST_W2", m["W2"])
        emit_array(f, "ST_B2", m["b2"])
        emit_array(f, "ST_W3", m["W3"])
        emit_array(f, "ST_B3", m["b3"])

        f.write("""static void st_model_params_load(st_model_t *m, st_bins_t *b)
{
    int i;
    m->W1 = ST_W1;  m->b1 = ST_B1;
    m->W2 = ST_W2;  m->b2 = ST_B2;
    m->W3 = ST_W3;  m->b3 = ST_B3;
    m->in_mean = ST_IN_MEAN;
    m->in_scale = ST_IN_SCALE;
    for (i = 0; i < ST_NUM_BINS + 1; ++i) b->cos_edges[i] = ST_COS_EDGES[i];
}

#endif /* ST_MODEL_PARAMS_H */
""")

    n = sum(int(np.asarray(m[k]).size) for k in
            ["W1", "b1", "W2", "b2", "W3", "b3"])
    print(f"wrote {path}")
    print(f"{n} parameters, {n * 4 / 1024:.0f} KiB as float32 in flash")


if __name__ == "__main__":
    main()
